# Generated by Django 2.2.5 on 2019-09-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=3500, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=3500, null=True, verbose_name='Description')),
                ('status', models.TextField(choices=[('Have to do', 'have_to_do'), ('In process', 'in_process'), ('Done', 'done')], default='have_to_do', max_length=50, verbose_name='Status')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Date of done')),
            ],
        ),
    ]
